version: '3.7'
services:
  vernemqq:
    depends_on: 
      - db
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
#    image: vernemq/vernemq
    build: ./vernemq/
    ports:
      - "8888:8888"
      - "1883:1883"
      - "8080:8080"

  db:
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
#    image: 'postgres'
    build: ./database/
    # ports:
    #   - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@developer-blog.net
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data: