version: '3.7'
services:
  vernemqq:
    depends_on:
      - db
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
#    image: vernemq/vernemq
    build: ./vernemq/
    ports:
      - "8888:8888"
      - "1883:1883"
      - "8080:8080"

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
#    image: 'postgres'
    build: ./database/
    # ports:
    #   - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgresdata: /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: flo@me.com
      PGADMIN_DEFAULT_PASSWORD: secretPassword
    restart: unless-stopped

volumes:
  postgresdata:
        external:
                name: ${WEBAPP_STORAGE_HOME}/posgtresql/
#    external: true
