version: '3.7'
services:
  vernemqq:
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on
      - DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST=db
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT=5432
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER=postgres
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD=somepassword
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE=postgres
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD=crypt
    image: vernemq/vernemq
    ports:
      - "8888:8888"
      - "1883:1883"
      - "8080:8080"
    networks:
      - kiskaiot
    restart: always
      
  db:
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
    image: 'postgres'
    # ports:
    #   - "5432:5432"
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./postgres-config:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kiskaiot

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: flo@me.com
      PGADMIN_DEFAULT_PASSWORD: secretPassword
      PGADMIN_LISTEN_PORT: 80
    restart: always
    networks:
      - kiskaiot

networks:
  kiskaiot:
    name: kiskaIOT
#volumes:
  # for this the setting WEBSITES_ENABLE_APP_SERVICE_STORAGE has to be true
  # https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#use-persistent-shared-storage
  #postgresdata: ${WEBAPP_STORAGE_HOME}/posgtresql/
  # for this two we are using a blob storage account
  # take a look here: https://stackoverflow.com/a/58883270
 # postgresconfig: /databaseconfig
  #   external: true
  #   name: postgresconfig
  #vernemqconf: /vernemqconfig
  #   external: true
  #   name: vernemqconf