version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: flo@me.com
      PGADMIN_DEFAULT_PASSWORD: seecretPassword
      PGADMIN_LISTEN_PORT: 80
    restart: always
